# Main configuration file
samtools:
  SamToBam:
    parent_task: ratatosk.lib.align.bwa.Sampe

picard:
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  SortSam:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  MergeSamFiles:
    target_generator_function: ratatosk.ext.scilife.sample.organize_sample_runs
    parent_task: ratatosk.lib.tools.picard.SortSam

gatk:
  ref: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seq/chr11.fa
  knownSites: [~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf]
  dbsnp: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf

  RealignerTargetCreator:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  IndelRealigner:
    parent_task: ratatosk.lib.tools.gatk.RealignerTargetCreator
  BaseRecalibrator:
    parent_task: ratatosk.lib.tools.gatk.IndelRealigner
  PrintReads:
    parent_task: ratatosk.lib.tools.gatk.BaseRecalibrator
  ClipReads:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  UnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.ClipReads
  VariantFiltration:
    parent_task: ratatosk.lib.tools.gatk.UnifiedGenotyper
  VariantEval:
    parent_task: ratatosk.lib.tools.gatk.VariantFiltration
