settings:
  target_generator_handler: ratatosk.ext.scilife.sample.target_generator

ratatosk.lib.tools.picard:
  SortSam:
    parent_task: ratatosk.lib.align.bwa.Bampe
  MergeSamFiles:
    parent_task: ratatosk.lib.tools.picard.SortSam
    target_generator_handler: ratatosk.ext.scilife.sample.collect_sample_runs
  InputBamFile:
    parent_task: ratatosk.lib.align.bwa.Bampe
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics

ratatosk.lib.tools.gatk:
  RealignerTargetCreator:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  IndelRealigner:
    parent_task:
      - ratatosk.lib.tools.picard.DuplicationMetrics
      - ratatosk.lib.tools.gatk.RealignerTargetCreator
  BaseRecalibrator:
    options: 
      - --covariate CycleCovariate
      - --covariate ContextCovariate
    parent_task: ratatosk.lib.tools.gatk.IndelRealigner
  PrintReads:
    diff_label:
      - .realign
      - 
      - .realign
    parent_task:
      - ratatosk.lib.tools.picard.DuplicationMetrics
      - ratatosk.lib.tools.gatk.BaseRecalibrator
      - ratatosk.lib.tools.picard.PicardMetrics
  UnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  SplitUnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  SelectSnpVariants:
    parent_task: ratatosk.lib.tools.gatk.CombineSplitVariants
  SelectIndelVariants:
    parent_task: ratatosk.lib.tools.gatk.CombineSplitVariants
  VariantSnpRecalibrator:
    parent_task: ratatosk.lib.tools.gatk.SelectSnpVariants
  VariantSnpRecalibratorExome:
    parent_task: ratatosk.lib.tools.gatk.SelectSnpVariants
  VariantIndelRecalibrator:
    parent_task: ratatosk.lib.tools.gatk.SelectIndelVariants
  VariantSnpFiltrationExp:
    parent_task: ratatosk.lib.tools.gatk.SelectSnpVariants
  VariantIndelFiltrationExp:
    parent_task: ratatosk.lib.tools.gatk.SelectIndelVariants
  VariantEval:
    parent_task: ratatosk.lib.tools.gatk.VariantFiltration
  ReadBackedPhasing:
    diff_label:
      - -variants-combined
      - 
    parent_task:
      - ratatosk.lib.tools.gatk.PrintReads
      - ratatosk.pipeline.seqcap.CombineFilteredVariants
  CombineVariants:
    options:
      - -minimalVCF
      - --sites_only
    parent_task:
      - ratatosk.lib.tools.gatk.VariantSnpEffAnnotator
    target_generator_handler: ratatosk.ext.scilife.sample.collect_vcf_files
    add_label:
      - .sort.merge.dup.realign.recal-variants-combined-phased-annotated

  VariantSnpEffAnnotator:
    parent_task: 
      - ratatosk.lib.tools.gatk.ReadBackedPhasing
      - ratatosk.lib.annotation.snpeff.snpEff
      - ratatosk.lib.annotation.snpeff.snpEffTxt

    add_label:
      - 
      - -effects
      - -effects
      
  SeqCapUnifiedGenotyperAlleles:
    parent_task:
      - ratatosk.lib.tools.gatk.PrintReads
      - ratatosk.lib.tools.gatk.CombineVariants
    diff_label:
      - -variants-combined-phased-annotated
      - 
ratatosk.lib.align.bwa:
  Aln:
    parent_task:
      - ratatosk.lib.align.bwa.InputFastqFile
      - ratatosk.lib.tools.fastqc.FastQC

ratatosk.lib.tools.fastqc:
  FastQC:
    parent_task:
      - ratatosk.lib.align.bwa.InputFastqFile
ratatosk.lib.annotation.snpeff:
  snpEff:
    parent_task:
      - ratatosk.lib.tools.gatk.ReadBackedPhasing
  snpEffTxt:
    parent_task:
      - ratatosk.lib.tools.gatk.ReadBackedPhasing
